### ISSUE TITLE
Refactor strlcpy for strcpy with a static_assert were possible in WWVegas

### ISSUE THREAD

**Issue by Skyaero42** [TheSuperHackers/GeneralsGameCode#1828]
Something is wrong with the following line. Perhaps this was meant to be strcpy. Buffer has same length as TGA2_SIGNATURE.
```cpp
strlcpy(footer.Signature, TGA2_SIGNATURE, sizeof(footer.Signature));
```

There are more copies that can use static_assert's instead.
```cpp
strlcpy(Name,w3d_data.Name,sizeof(Name));
```
```cpp
strlcpy(header.Name,AnimName,sizeof(header.Name));
strlcpy(header.HierarchyName,HierarchyName,sizeof(header.HierarchyName));
```
```cpp
strlcpy(Name, aheader.HierarchyName, ARRAY_SIZE(Name));
strlcat(Name, ".", ARRAY_SIZE(Name));
strlcat(Name, aheader.Name, ARRAY_SIZE(Name));
```
```cpp
strlcpy(HierarchyName,aheader.HierarchyName,W3D_NAME_LEN);
```

WWVegas code needs another review pass to use static_assert + strcpy instead of strlcpy where so possible.

**Comment by Skyaero42** [comment]
Resolved with #1808

**Comment by xezon** [comment]
`strlcpy(footer.Signature, TGA2_SIGNATURE, sizeof(footer.Signature));` was not fixed.
